# Generated by Django 5.0.4 on 2024-04-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=100)),
                ('resposta', models.TextField()),
                ('data_e_hora', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
