# Generated by Django 5.0.4 on 2024-04-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frases',
            name='categoria',
            field=models.CharField(choices=[('POSITIVO', 'Positivo'), ('NEGATIVO', 'Negativo'), ('NEUTRO', 'Neutro')], default='', max_length=100),
        ),
    ]
