# Generated by Django 5.0.4 on 2024-04-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisador', '0002_frases_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='frases',
            name='publicada',
            field=models.BooleanField(default=True),
        ),
    ]
